### ISSUE TITLE
Build error when setting DefaultMap and PartialMaps to ""

### ISSUE THREAD

**Issue by rossipedia** [kiibohd/controller#13]
I'm trying to start from the ground up to get a good feel for how to build layout maps, and I figured I'd try with just the default/scan map.

Per the docs in `CMakeLists.txt`:

```
##| Layer additonal .kll maps on the BaseMap, layers are in order from 1st to nth
##| Can be set to "" 
set(  DefaultMap "md1Overlay stdFuncMap"
	CACHE STRING "KLL DefaultMap" )

##| ParitalMaps available on top of the BaseMap. See above for syntax on specifying multiple layers vs. layering
##| Can be set to ""
set( PartialMaps "hhkbpro2"
	CACHE STRING "KLL PartialMaps/Layer Definitions" )
```

Both explicitly say `Can be set to ""`

I figure "cool", and issue the following from a fresh checkout:

```bash
~/code/controller$ mkdir build_infinity
~/code/controller$ cd build_infinity
~/code/controller/build_infinity$ cmake -DDefaultMap="" -DPartialMaps="" ..
[... blah blah blah ...]
~/code/controller/build_infinity$ make
[  5%] Generating KLL Layout
Traceback (most recent call last):
  File "../kll/kll.py", line 640, in <module>
    gitChanges
  File "/home/kb/code/controller/kll/backends/kiibohd.py", line 109, in process
    for file, name in zip( variables.layerVariables[0]['*LayerFiles'], variables.layerVariables[0]['*NameStack'] ):
KeyError: '*LayerFiles'
CMakeFiles/kiibohd.elf.dir/build.make:55: recipe for target 'generatedKeymap.h' failed
make[2]: *** [generatedKeymap.h] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/kiibohd.elf.dir/all' failed
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
Makefile:72: recipe for target 'all' failed
make: *** [all] Error 2
```

Death. Destruction. And no flashable firmware.

I am a sad panda

![sad panda](http://i.imgur.com/8npPghu.jpg)

I'll dig in a bit more and see if I can submit a PR, but it seems like a quick fix and you might be able to take care of it super quick.

**Comment by haata** [comment]
Fixed b7a897986418b83d5037ebc14f659ec046457c45
