### ISSUE TITLE
make[1]: *** [CMakeFiles/kiibohd.dir/all] Error 2

### ISSUE THREAD

**Issue by benoittgt** [kiibohd/controller#226]
Hello

I have an issue when trying to use the `ergodox-*.bash`.

I already use the script few month ago but when I tried recently with repo updated I was not able to use it properly (with paritialsmaps).

I'm using 4406dd4 and followed this guide https://github.com/kiibohd/controller/tree/master/Keyboards#example-usage

Here is the full log : 
<details>

```sh
» bash ergodox-r.bash
darwin16/macOS is supported.
Selected Generator: Unix Makefiles
darwin16.lirik_ergodox_r.gcc.make
-- Build CPU Detected:
x86_64
-- Build OS Detected:
Darwin 16.7.0
-- Compiler Family:
arm
-- Compiler Selected:
gcc
-- Chip Selected:
mk20dx256vlh7
-- Chip Family:
mk20dx
-- CPU Selected:
cortex-m4
-- Compiler Source Files:
Lib/mk20dx.c;Lib/delay.c;Lib/entropy.c;Lib/time.c
-- Bootloader Type:
dfu
-- Full Compiler:
/usr/local/bin/arm-none-eabi-gcc 6.2.1
-- Detected Scan Module Source Files:
Scan/Devices/ISSILed/i2c.c;Scan/Devices/ISSILed/led_scan.c;Scan/Devices/MatrixARM/matrix_scan.c;Scan/Devices/STLcd/lcd_scan.c;Scan/Devices/UARTConnect/connect_scan.c;Scan/Infinity_Ergodox/scan_loop.c
-- Detected Macro Module Source Files:
Macro/PartialMap/macro.c;Macro/PartialMap/result.c;Macro/PartialMap/trigger.c;Macro/PixelMap/pixel.c;/Users/bti/code/controller/Keyboards/darwin16.lirik_ergodox_r.gcc.make/generatedPixelmap.c
-- Detected Output Module Source Files:
Output/HID-IO/hidio_com.c;Output/pjrcUSB/output_com.c;Output/pjrcUSB/arm/usb_desc.c;Output/pjrcUSB/arm/usb_dev.c;Output/pjrcUSB/arm/usb_joystick.c;Output/pjrcUSB/arm/usb_keyboard.c;Output/pjrcUSB/arm/usb_mem.c;Output/pjrcUSB/arm/usb_mouse.c;Output/pjrcUSB/arm/usb_rawio.c;Output/pjrcUSB/arm/usb_serial.c
-- Detected Debug Module Source Files:
Debug/cli/cli.c;Debug/led/led.c;Debug/print/print.c
ctags: Warning: unknown regex flag: ')'
0 files, 0 lines (0 kB) scanned in 0.0 seconds (0 kB/s)
6 tags added to tag file
6 tags sorted in 0.00 seconds
-- Detected Layout Files:
/Users/bti/code/controller/Scan/Devices/ISSILed/capabilities.kll
/Users/bti/code/controller/Scan/Devices/MatrixARM/capabilities.kll
/Users/bti/code/controller/Scan/Devices/STLcd/capabilities.kll
/Users/bti/code/controller/Scan/Devices/UARTConnect/capabilities.kll
/Users/bti/code/controller/Macro/PartialMap/capabilities.kll
/Users/bti/code/controller/Macro/PixelMap/capabilities.kll
/Users/bti/code/controller/Output/HID-IO/capabilities.kll
/Users/bti/code/controller/Output/pjrcUSB/capabilities.kll
/Users/bti/code/controller/Scan/Infinity_Ergodox/scancode_map.kll
/Users/bti/code/controller/Scan/Infinity_Ergodox/rightHand.kll
/Users/bti/code/controller/Scan/Infinity_Ergodox/slave1.kll
/Users/bti/code/controller/Scan/Infinity_Ergodox/leftHand.kll
/Users/bti/code/controller/kll/layouts/mine/MDErgo1-Default-0.kll
/Users/bti/code/controller/kll/layouts/infinity_ergodox/lcdFuncMap.kll
/Users/bti/code/controller/kll/layouts/mine/MDErgo1-Default-1.kll
/Users/bti/code/controller/kll/layouts/infinity_ergodox/lcdFuncMap.kll
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bti/code/controller/Keyboards/darwin16.lirik_ergodox_r.gcc.make
[  3%] Generating KLL Layout
kll BETA 0.5c.f0f1032e4690f103be99d616c17d0c22a2a7633c - 2017-10-14 15:44:22 -0700
Traceback (most recent call last):
  File "../../kll/kll", line 159, in <module>
    control.process()
  File "/Users/bti/code/controller/kll/common/stage.py", line 123, in process
    stage.process()
  File "/Users/bti/code/controller/kll/common/stage.py", line 2827, in process
    self.emitter.process()
  File "/Users/bti/code/controller/kll/emitters/kiibohd/kiibohd.py", line 671, in process
    self.fill_dict['ResultMacros'] += "{0}, ".format(self.result_combo_conversion(combo))
  File "/Users/bti/code/controller/kll/emitters/kiibohd/kiibohd.py", line 249, in result_combo_conversion
    cap_index = self.capabilities_index[identifier.name]
KeyError: 'None'
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.dir/all] Error 2
make: *** [all] Error 2
Error in make. Exiting..
```
</details>

My `ergodox-r.bash` where I had to comment the check on `"${BASH_SOURCE%/*}/cmake.bash"` and source path to let cmake.bash be able to run : 

<details>

```sh
#!/usr/bin/env bash
#
# Keyboard: Ergodox
#
# These build scripts are just a convenience for configuring your keyboard (less daunting than CMake)
# Jacob Alexander 2015-2017



#################
# Configuration #
#################

# Feel free to change the variables in this section to configure your keyboard

BuildPath="lirik_ergodox_r"

## KLL Configuration ##

# Generally shouldn't be changed, this will affect every layer
BaseMap="scancode_map rightHand slave1 leftHand"

# This is the default layer of the keyboard
# NOTE: To combine kll files into a single layout, separate them by spaces
# e.g.  DefaultMap="mylayout mylayoutmod"
DefaultMap="mine/MDErgo1-Default-0 infinity_ergodox/lcdFuncMap"

# This is where you set the additional layers
# NOTE: Indexing starts at 1
# NOTE: Each new layer is another array entry
# e.g.  PartialMaps[1]="layer1 layer1mod"
#       PartialMaps[2]="layer2"
#       PartialMaps[3]="layer3"
PartialMaps[1]="mine/MDErgo1-Default-1 infinity_ergodox/lcdFuncMap"

##########################
# Advanced Configuration #
##########################

# Don't change the variables in this section unless you know what you're doing
# These are useful for completely custom keyboards
# NOTE: Changing any of these variables will require a force build to compile correctly

# Keyboard Module Configuration
ScanModule="Infinity_Ergodox"
MacroModule="PixelMap"
OutputModule="pjrcUSB"
DebugModule="full"

# Microcontroller
Chip="mk20dx256vlh7"

# Compiler Selection
Compiler="gcc"


########################
# Bash Library Include #
########################

# Shouldn't need to touch this section

# Check if the library can be found
# if [ ! -f "${BASH_SOURCE%/*}/cmake.bash" ]; then
# 	echo "ERROR: Cannot find 'cmake.bash'"
# 	exit 1
# fi

# Load the library
source "cmake.bash"
```
</details>

The diff if needed:

<details>

```diff
--- a/Keyboards/ergodox-r.bash
+++ b/Keyboards/ergodox-r.bash
@@ -13,7 +13,7 @@

 # Feel free to change the variables in this section to configure your keyboard

-BuildPath="ICED-R"
+BuildPath="lirik_ergodox_r"

 ## KLL Configuration ##

@@ -23,7 +23,7 @@ BaseMap="scancode_map rightHand slave1 leftHand"
 # This is the default layer of the keyboard
 # NOTE: To combine kll files into a single layout, separate them by spaces
 # e.g.  DefaultMap="mylayout mylayoutmod"
-DefaultMap="infinity_ergodox/mdergo1Overlay infinity_ergodox/lcdFuncMap"
+DefaultMap="mine/MDErgo1-Default-0 infinity_ergodox/lcdFuncMap"

 # This is where you set the additional layers
 # NOTE: Indexing starts at 1
@@ -31,10 +31,7 @@ DefaultMap="infinity_ergodox/mdergo1Overlay infinity_ergodox/lcdFuncMap"
 # e.g.  PartialMaps[1]="layer1 layer1mod"
 #       PartialMaps[2]="layer2"
 #       PartialMaps[3]="layer3"
-PartialMaps[1]="infinity_ergodox/iced_func"
-PartialMaps[2]="infinity_ergodox/iced_numpad"
-
-
+PartialMaps[1]="mine/MDErgo1-Default-1 infinity_ergodox/lcdFuncMap"

 ##########################
 # Advanced Configuration #
@@ -65,10 +62,10 @@ Compiler="gcc"
 # Shouldn't need to touch this section

 # Check if the library can be found
-if [ ! -f "${BASH_SOURCE%/*}/cmake.bash" ]; then
-       echo "ERROR: Cannot find 'cmake.bash'"
-       exit 1
-fi
+# if [ ! -f "${BASH_SOURCE%/*}/cmake.bash" ]; then
+#      echo "ERROR: Cannot find 'cmake.bash'"
+#      exit 1
+# fi

 # Load the library
-source "${BASH_SOURCE%/*}/cmake.bash"
+source "cmake.bash"
(END)
```

</details>

I attached my two kll file (renamed with txt to be accessible on github).

[MDErgo1-Default-0.kll.txt](https://github.com/kiibohd/controller/files/1403970/MDErgo1-Default-0.kll.txt)
[MDErgo1-Default-1.kll.txt](https://github.com/kiibohd/controller/files/1403971/MDErgo1-Default-1.kll.txt)

The problem go away when I remove the `PartialMaps[1]="mine/MDErgo1-Default-1 infinity_ergodox/lcdFuncMap"`

**Comment by benoittgt** [comment]
Ok I finally removed led control and "none" from the KLL and it's working.

**Comment by benoittgt** [comment]
Led control generate from https://input.club/configurator-ergodox/ are incorrect. It gave 3 parameter when the method wants 2.
