### ISSUE TITLE
Error building infinity.bash under OSX 10.11 (El Capitan)

### ISSUE THREAD

**Issue by nemtsov** [kiibohd/controller#64]
There's an issue in OSX 10.11 (El Capitan) where certain mechanical keyboards (infinity keyboard in particular) don't work (but are recognized in System Information).

It is also reported here for ducky keyboards (http://apple.stackexchange.com/questions/208576/mechanical-keyboard-stopped-working-after-upgrading-to-el-capitan/209174#209174).

So, hoping that updating to the latest firmware will solve the problem, I attempted to build `controller` and got the errors below. I appreciate any help you can provide on this, as typing without my keyboard sucks. (I also tried the VM to avoid build ussues, but since the keyboard is in a weird state the VM does not recognize it.)

Thanks!

```
➜  Keyboards git:(master) ./infinity.bash
-- Compiler Family:
arm
-- Compiler Selected:
gcc
-- Chip Selected:
mk20dx128vlf5
-- Chip Family:
mk20dx
-- CPU Selected:
cortex-m4
-- Compiler Source Files:
Lib/mk20dx.c;Lib/delay.c
-- Bootloader Type:
dfu
-- Detected Scan Module Source Files:
Scan/MatrixARM/matrix_scan.c;Scan/MD1/scan_loop.c
-- Detected Macro Module Source Files:
Macro/PartialMap/macro.c
-- Detected Output Module Source Files:
Output/pjrcUSB/output_com.c;Output/pjrcUSB/arm/usb_desc.c;Output/pjrcUSB/arm/usb_dev.c;Output/pjrcUSB/arm/usb_joystick.c;Output/pjrcUSB/arm/usb_keyboard.c;Output/pjrcUSB/arm/usb_mem.c;Output/pjrcUSB/arm/usb_mouse.c;Output/pjrcUSB/arm/usb_serial.c
-- Detected Debug Module Source Files:
Debug/cli/cli.c;Debug/led/led.c;Debug/print/print.c
-- Found Git: /usr/local/bin/git (found version "2.2.1")
-- Found Ctags: /usr/bin/ctags
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/delay.c and /Users/yuriy/wd/kiibohd-controller/Lib/delay.c: micros (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/delay.c and /Users/yuriy/wd/kiibohd-controller/Lib/delay.c: delay (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.c and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.c: fault_isr (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/delay.h and /Users/yuriy/wd/kiibohd-controller/Lib/delay.h: _delay_ms (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/delay.h and /Users/yuriy/wd/kiibohd-controller/Lib/delay.h: _delay_us (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/delay.h and /Users/yuriy/wd/kiibohd-controller/Lib/delay.h: millis (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/delay.h and /Users/yuriy/wd/kiibohd-controller/Lib/delay.h: delayMicroseconds (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/Interrupts.h and /Users/yuriy/wd/kiibohd-controller/Lib/Interrupts.h: cli (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/Interrupts.h and /Users/yuriy/wd/kiibohd-controller/Lib/Interrupts.h: sei (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: PORT_PCR_IRQC (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: PORT_PCR_MUX (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SIM_SOPT2_CLKOUTSEL (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SIM_CLKDIV1_OUTDIV1 (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SIM_CLKDIV1_OUTDIV2 (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SIM_CLKDIV1_OUTDIV4 (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SIM_CLKDIV2_USBDIV (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SMC_PMCTRL_RUNM (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SMC_PMCTRL_STOPM (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: SMC_VLLSCTRL_VLLSM (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: PMC_LVDSC1_LVDV (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: PMC_LVDSC2_LVWV (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: MCM_CR_SRAMLAP (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: MCM_CR_SRAMUAP (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: AXBS_CRS_PARK (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_CEEI_CEEI (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_SEEI_SEEI (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_CERQ_CERQ (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_SERQ_SERQ (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_CDNE_CDNE (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_SSRT_SSRT (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_CERR_CERR (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_CINT_CINT (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_DCHPRI_CHPRI (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_ATTR_SMOD (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_ATTR_SSIZE (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_ATTR_DMOD (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_ATTR_DSIZE (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_CSR_BWC (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_CSR_MAJORLINKCH (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_NBYTES_MLOFFNO_NBYTES (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_NBYTES_MLOFFYES_NBYTES (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h and /Users/yuriy/wd/kiibohd-controller/Lib/mk20dx.h: DMA_TCD_NBYTES_MLOFFYES_MLOFF (Warning only)
Duplicate entry in file /Users/yuriy/wd/kiibohd-controller/Scan/MD1/scan_loop.c, line 94: processed
Second entry ignored
Duplicate entry in file /Users/yuriy/wd/kiibohd-controller/Macro/PartialMap/kll.h, line 44: var_uint_t
Second entry ignored
Duplicate entry in file /Users/yuriy/wd/kiibohd-controller/Macro/PartialMap/kll.h, line 46: var_uint_t
Second entry ignored
Duplicate entry in file /Users/yuriy/wd/kiibohd-controller/Macro/PartialMap/kll.h, line 59: nat_ptr_t
Second entry ignored
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Scan/MatrixARM/matrix_scan.h: __attribute__ (Warning only)
Duplicate entry in file /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c, line 860: index
Second entry ignored
Duplicate entry in file /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c, line 861: stat2bufferdescriptor
Second entry ignored
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c: LSB (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c: MSB (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c: usb_string_descriptor_struct (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c: usb_string_descriptor (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.c: iInterfaceString (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c: BDT_PID (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c: BDT_DESC (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c: index (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c: stat2bufferdescriptor (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c: bdt_t (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c: endpoint0_transmit (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.c: usb_setup (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_joystick.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_joystick.c: usb_joystick_send (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_keyboard.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_keyboard.c: usb_keyboard_send (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mem.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mem.c: usb_free (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c: usb_mouse_buttons (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c: usb_mouse_move (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c: usb_mouse_position (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mouse.c: usb_mouse_screen_size (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: settings (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_getchar (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_peekchar (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_available (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_read (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_flush_input (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_putchar (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_write (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_flush_output (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.c: usb_serial_flush_callback (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.h and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.h: usb_descriptor_list_t (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.h and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_desc.h: endpoints (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.h and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.h: usb_device_software_reset (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.h and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_dev.h: usb_rx_byte_count (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mem.h and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_mem.h: usb_packet_t (Warning only)
Duplicate entry in files /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.h and /Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/arm/usb_serial.h: PSTR (Warning only)
Duplicate entry in file /Users/yuriy/wd/kiibohd-controller/Debug/print/print.h, line 87: print
Second entry ignored
-- Downloading latest kll version:
Cloning into 'kll'...
remote: Counting objects: 378, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 378 (delta 1), reused 0 (delta 0), pack-reused 370
Receiving objects: 100% (378/378), 151.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (203/203), done.
Checking connectivity... done.
-- Detected Layout Files:
/Users/yuriy/wd/kiibohd-controller/Scan/MatrixARM/capabilities.kll
/Users/yuriy/wd/kiibohd-controller/Macro/PartialMap/capabilities.kll
/Users/yuriy/wd/kiibohd-controller/Output/pjrcUSB/capabilities.kll
/Users/yuriy/wd/kiibohd-controller/Scan/MD1/defaultMap.kll
/Users/yuriy/wd/kiibohd-controller/kll/layouts/md1Overlay.kll
/Users/yuriy/wd/kiibohd-controller/kll/layouts/stdFuncMap.kll
/Users/yuriy/wd/kiibohd-controller/kll/layouts/hhkbpro2.kll
-- Found DFU_SUFFIX: /usr/local/bin/dfu-suffix (found version "0.8")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yuriy/wd/kiibohd-controller/Keyboards/IC60
[  5%] Generating KLL Layout
ERROR: '{' is an invalid USB HID Code Lookup...
Traceback (most recent call last):
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 323, in _some
    raise NoParseError('got unexpected token', s)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 182, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 323, in _some
    raise NoParseError('got unexpected token', s)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 323, in _some
    raise NoParseError('got unexpected token', s)
funcparserlib.parser.NoParseError: got unexpected token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../kll/kll.py", line 757, in <module>
    processKLLFile( filename )
  File "../../kll/kll.py", line 689, in processKLLFile
    tree = parse( tokenSequence )
  File "../../kll/kll.py", line 679, in parse
    return kll_file.parse( tokenSequence )
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 122, in parse
    (tree, _) = self.run(tokens, State())
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 293, in _many
    (v, s) = p.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 182, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 180, in _or
    return self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 158, in _add
    (v1, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 182, in _or
    return other.run(tokens, State(s.pos, e.state.max))
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 200, in _shift
    (v, s2) = self.run(tokens, s)
  File "/Users/yuriy/wd/kiibohd-controller/kll/funcparserlib/parser.py", line 201, in _shift
    return f(v), s2
  File "../../kll/kll.py", line 235, in make_usbCode
    return make_hidCode( 'USBCode', token )
  File "../../kll/kll.py", line 205, in make_hidCode
    hidCode = kll_hid_lookup_dictionary[ type ][ token[1:-1].upper() ][1]
KeyError: '{'
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
make: *** [all] Error 2
Firmware has been compiled into: 'IC60'
/Users/yuriy/wd/kiibohd-controller/Keyboards
```

**Comment by haata** [comment]
Oops, really sorry about that. I fixed a symbolic name in KLL (has been wrong for a really long time) and forgot to update the hhkbpro2 kll file.

Do a git pull in the kll directory and it should fix the issue.

https://github.com/kiibohd/kll/commit/c3ec73860d8e163b61130a7d893d293144b88324

Let me know if you have any other issues.

**Comment by nemtsov** [comment]
That fixed the error; thanks! (let's hope it fixes the usb issue too. will report here for future reference)
